# workflow/Snakefile

configfile: "config/config.yaml"

rule all:
    input:
        expand("results/processing_groups/{processing_group}/scaled.expt", processing_group=config["processing_groups"]),
        expand("results/processing_groups/{processing_group}/visualization.ipynb", processing_group=config["processing_groups"]),
        expand("results/processing_groups/{processing_group}/scaling_model.ipynb", processing_group=config["processing_groups"]),
        
include: "rules/common.smk" 
include: "rules/dials.smk"
include: "rules/mdx2.smk"